# Simple workflow for deploying generated content to GitHub Pages
name: Deploy generated content to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions to allow deployment
permissions:
  contents: write

# Run job to deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: python3 build_docs.py
      - run: mkdocs gh-deploy --force
